### ISSUE TITLE
KeyError: 'RAY'

### ISSUE THREAD

**Issue by kevin-valerio** [FlyinDoji/ftx#1]
```
Traceback (most recent call last):
  File "/Users/kevin/Desktop/toz.py", line 14, in <module>
    spot_fills, futures_fills, futures_by_market, spot_by_market = fills_history(c)
  File "/opt/homebrew/lib/python3.9/site-packages/ftx/data/fetch.py", line 22, in fills_history
    return preprocess_fills(df)
  File "/opt/homebrew/lib/python3.9/site-packages/ftx/data/_wranglers.py", line 74, in preprocess_fills
    futures = convert_futures_size(futures)
  File "/opt/homebrew/lib/python3.9/site-packages/ftx/data/_wranglers.py", line 20, in convert_futures_size
    futures_fills.loc[futures_fills['market'].str.contains(mkt), 'size'] = futures_fills.loc[futures_fills['market'].str.contains(mkt), 'size'].apply(decimal_with_precision, args=(prec.FUTURES_SIZE[mkt], ))
KeyError: 'RAY'
```

Error with this following code:

```
from ftx.clients.rest_client import FtxAuth, FtxClient
from ftx.data.fetch import fills_history, funding_history, open_positions
from ftx.data.process import get_futures_summary, get_spot_summary, get_futures_trades_by_market
from tabulate import tabulate
import pandas as pd

pd.options.display.float_format = "{:,.2f}".format

key = 'X'
secret = 'X'
auth = FtxAuth(key, secret, '') # OR NONE IF MAIN ACCOUNT

c = FtxClient(auth)
spot_fills, futures_fills, futures_by_market, spot_by_market = fills_history(c)
funding = funding_history(c)
open_pos = open_positions(c)
df = get_futures_summary(futures_fills, funding, open_pos)
print(tabulate(df, headers='keys', tablefmt='psql'))

```

Any idea why? Thanks!

**Comment by FlyinDoji** [comment]
The _precisions.py doesn't have an entry for RAY because it wasn't listed on FTX at the time I made this.
I only added entries for the coins I myself traded. Didn't get the chance to add functionality to get precision info for each asset directly from their API. You could try adding the entry yourself, I don't trade much these days but if I ever get back to it i might give this a refresh.

**Comment by FlyinDoji** [comment]
Issue should be resolved now, the tool will pull asset size and price precisions from the API so it will work regardless of the assets in your trading history.
